


<TestCustom>:

    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: 'vertical'

        ActionBarCustom:

        Button:
            text: 'World'
            on_press: print('Hello world')
        Label:
            text: 'Hello'

        BoxLayout:
            id: letters
        BoxLayout:
            id: numbers
        BoxLayout:
            id: keypad

<CustomButton>:
    color: app.theme['gui_button_text']
    background_color: app.theme['gui_button']
#    font_size: 20
    on_release: root.custom_callback()  # Define your custom behavior here
