<DashboardScreen>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Dashboard Screen"
        Button:
            text: "Go to Login"
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "login"
        Button:
            text: "Go to Settings"
            on_release:
                root.manager.transition.direction = "left"
                root.manager.current = "settings"
